Fix requirements.txt format
I was not able to "pip install -r requirements.txt" without this change
because of this error (since python_version isn't a package):

ERROR: Could not find a version that satisfies the requirement python_version=="^3.6" (from versions: 0.0.2)
ERROR: No matching distribution found for python_version=="^3.6"